services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon # or change to your preferred Render region
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: PORT
        value: 5678
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: WEBHOOK_URL
        value: https://n8n-9tz3.onrender.com
